In [5]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv("framingham.csv")
df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

In [3]:
df = df.fillna(df.mode().iloc[0])

In [4]:
X = df[['male','age','education','currentSmoker','cigsPerDay','BPMeds','prevalentStroke','prevalentHyp','diabetes','totChol','sysBP','diaBP','BMI','heartRate','glucose']]
y = df['TenYearCHD']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

model = RandomForestRegressor(n_estimators=100,random_state=0)
model.fit(X_train,y_train)

RandomForestRegressor(random_state=0)

In [6]:
y_pred = model.predict(X_test)

In [7]:
mse = mean_squared_error(y_test,y_pred)
mse

np.float64(0.12627051886792454)

In [8]:
new_data = pd.DataFrame({'male':[0],
                         'age':[80],
                         'education':[1],
                         'currentSmoker':[1],
                         'cigsPerDay':[2],
                         'BPMeds':[0],
                         'prevalentStroke':[1],
                         'prevalentHyp':[1],
                         'diabetes':[0],
                         'totChol':[210],
                         'sysBP':[150],
                         'diaBP':[90],
                         'BMI':[20],
                         'heartRate':[110],
                         'glucose':[50]})

In [9]:
y_pred = model.predict(new_data)
y_pred

array([0.48])

In [10]:
new_data2 = pd.DataFrame({'male':[1],
                         'age':[23],
                         'education':[0.8],
                         'currentSmoker':[0],
                         'cigsPerDay':[0],
                         'BPMeds':[0],
                         'prevalentStroke':[0],
                         'prevalentHyp':[0],
                         'diabetes':[0],
                         'totChol':[80],
                         'sysBP':[110],
                         'diaBP':[90],
                         'BMI':[21],
                         'heartRate':[82],
                         'glucose':[90]})

In [11]:
y_pred = model.predict(new_data2)
y_pred

array([0.07])

In [13]:
new_data3 = pd.DataFrame({'male':[0],
                         'age':[80],
                         'education':[1],
                         'currentSmoker':[1],
                         'cigsPerDay':[2],
                         'BPMeds':[0],
                         'prevalentStroke':[1],
                         'prevalentHyp':[1],
                         'diabetes':[0],
                         'totChol':[210],
                         'sysBP':[150],
                         'diaBP':[90],
                         'BMI':[29],
                         'heartRate':[110],
                         'glucose':[100]})

In [14]:
y_pred = model.predict(new_data3)
y_pred

array([0.54])

In [12]:
importances = model.feature_importances_
print(f"Feature Importances: {importances}")

Feature Importances: [0.01693344 0.11896041 0.03599513 0.00518859 0.05230248 0.00473579
 0.00492408 0.01550637 0.00413665 0.13378219 0.13739752 0.1042903
 0.14689663 0.09719788 0.12175254]
